-- AlterTable
ALTER TABLE "pay" ALTER COLUMN "value" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "status" DROP DEFAULT;

-- AlterTable
ALTER TABLE "receive" ALTER COLUMN "value" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "status" DROP DEFAULT;
